= VMware Tanzu Mission Control Demo (EKS w/ALB)

== About 

This is a guick guide to depoly a TMC managed EKS cluster with AWS ALB and starter application.  This guide will 
walk through the process of setting up the reauired VPC and  AWS credentials TMC needs to deploy a three node EKS 
cluster. AWS Application Load Balancer will be enabled and a common sample app deployed to the Kubernetes cluster.  
Various verification and troubleshooting steps will be performed throughtou this tutorial as well.

== Assumptions

* You have access to AWS, and your organizization has provided you access to Tanzu Mission Control (TMC).  

= Part 1 - Requirements
If you are currently already developing with EKS and Kubernetes, feel free to skip to Part 2. Otherwise, visit 
link:https://github.com/bbertka/setup-eks-dev-env[Setting up your EKS Dev Environment] for instructions on how to 
set up your machine with the proper tools needed to continue this lab.

. Generate a Tanzu API key and install the Tanzu CLI by logging into your organization's TMC instance, then 
navigate to the lower left panel and select "Automation Center".  Follow the instructions there to Get an API 
token, Initialize the CLI and log in, and Try out the CLI.  You have completed this step successfully if you can 
return the following output from the commands:
+
----
$ tanzu plugin list
Standalone Plugins
  NAME                DESCRIPTION                                                        TARGET      DISCOVERY  VERSION  STATUS
  isolated-cluster    isolated-cluster operations                                                    default    v0.28.0  installed
  login               Login to the platform                                                          default    v0.28.0  installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)              default    v0.28.0  installed
  management-cluster  Kubernetes management-cluster operations                           kubernetes  default    v0.28.0  installed
  package             Tanzu package management                                           kubernetes  default    v0.28.0  installed
  secret              Tanzu secret management                                            kubernetes  default    v0.28.0  installed
  telemetry           Configure cluster-wide telemetry settings                          kubernetes  default    v0.28.0  installed
----

. Next, follow the link:https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/services/tanzu-cli-ref-tmc/quickstart.html[Tanzu quickstart guide here] to create a TMC context, and sync your TMC 
plugins. Follow all the steps through "Verify your updated plug-ins".  You have completed this step properly if you can generate the following output with the command:
+
----
$ tanzu plugin list
Standalone Plugins
  NAME                DESCRIPTION                                                        TARGET      DISCOVERY  VERSION  STATUS
  isolated-cluster    isolated-cluster operations                                                    default    v0.28.0  installed
  login               Login to the platform                                                          default    v0.28.0  installed
  pinniped-auth       Pinniped authentication operations (usually not directly invoked)              default    v0.28.0  installed
  management-cluster  Kubernetes management-cluster operations                           kubernetes  default    v0.28.0  installed
  package             Tanzu package management                                           kubernetes  default    v0.28.0  installed
  secret              Tanzu secret management                                            kubernetes  default    v0.28.0  installed
  telemetry           Configure cluster-wide telemetry settings                          kubernetes  default    v0.28.0  installed

Plugins from Context:  south
  NAME                DESCRIPTION                                                     TARGET           VERSION  STATUS
  account             Account for tmc resources                                       mission-control  v0.0.1   installed
  agentartifacts      helm for tmc resources                                          mission-control  v0.0.1   installed
  apply               Create/Update a resource with a resource file                   mission-control  v0.0.1   installed
  audit               Run an audit request on an org                                  mission-control  v0.0.1   installed
  cluster                                                                             mission-control  v0.0.1   installed
  clustergroup        A group of Kubernetes clusters                                  mission-control  v0.0.1   installed
  continuousdelivery  Continuousdelivery for tmc resources                            mission-control  v0.0.1   installed
  data-protection     Data protection for tmc resources                               mission-control  v0.0.1   installed
  ekscluster                                                                          mission-control  v0.0.1   installed
  events              Events for any meaningful user activity or system state change  mission-control  v0.0.1   installed
  helm                helm for tmc resources                                          mission-control  v0.0.1   installed
  iam                 IAM Policies for tmc resources                                  mission-control  v0.0.1   installed
  inspection          Inspection for tmc resources                                    mission-control  v0.0.1   installed
  integration         Get available integrations and their information from registry  mission-control  v0.0.1   installed
  management-cluster  A TMC registered Management cluster                             mission-control  v0.0.1   installed
  policy              Policy for tmc resources                                        mission-control  v0.0.1   installed
  secret              secret for tmc resources                                        mission-control  v0.0.1   installed
  setting             Setting plugin for tmc resources                                mission-control  v0.0.1   installed
  tanzupackage        Tanzupackage for tmc resources                                  mission-control  v0.0.1   installed
  workspace           A group of Kubernetes namespaces                                mission-control  v0.0.1   installed
----

. Finally, now that your machine is ready for working with Tanzu, navigate back to the TMC GUI to create your first cluster.  


